name-template: 'Release v$NEXT_PATCH_VERSION 🌟'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 New Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🛠 Maintenance'
    label: 'maintenance'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |

 ## What's Changed
  $CHANGES

  **Full Changelog**: https://github.com/$REPOSITORY/compare/$PREVIOUS_TAG...$TAG
