name: Build and Release Package

on:
  push:
    branches: ['release']  
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create release package (Zip)
      run: |
        zip -r mqtt-pipy.zip ./* -x "*/.*"

    - name: Create release package (Tarball)
      run: |
        tar --exclude='.[^/]*' -czvf mqtt-pipy.tar.gz ./*

    - name: Upload release asset
      uses: actions/upload-artifact@v3
      with:
        name: release-package
        path: mqtt-pipy.zip # or mqtt-pipy.tar.gz

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Publish GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          Release version ${{ github.ref }}.
      env:
        GITHUB_TOKEN: ${{ secrets.WF_GITHUB_TOKEN }}
        
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: mqtt-pipy.zip # or mqtt-pipy.tar.gz
        asset_name: mqtt-pipy.zip # or mqtt-pipy.tar.gz
        asset_content_type: application/zip # or application/gzip
